[projects.weather-forecast]
name="Weather Forecast"
description="something"
technologies=[]
url="www.apfs.com.br"

[projects.rent-calculator]
name="Rent Calculator"
description="something"
technologies=[]